# Generated by Django 3.2.4 on 2021-07-14 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo_Subasta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ask', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('bid', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('minganancia', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('duracion_min', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('precio_alcanzado', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('nombre_art', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coleccionista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('nombre2', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50, null=True)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=13)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Costo_envio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('extra', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('recargo', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('embalaje', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('seguro', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Divisa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iva', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_fundacion', models.DateField()),
                ('pagina', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('proposito', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Antiguedades', 'antiguedades'), ('Galeria', 'galeria'), ('Numismatica', 'numismatica')], max_length=70)),
                ('alcance', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subasta_Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('tipo_puja', models.CharField(choices=[('Cerrada', 'cerrada'), ('Dinamica', 'dinamica')], max_length=50)),
                ('costo_cliente', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('costo_general', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('direccion', models.CharField(max_length=50)),
                ('costo_envio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AA.costo_envio')),
                ('lugar', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='AA.pais')),
                ('tiendas', models.ManyToManyField(to='AA.Tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Reglonfactura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('descripcion', models.CharField(max_length=50, null=True)),
                ('articulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AA.articulo_subasta')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AA.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coleccionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AA.coleccionista')),
                ('factura_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='AA.factura')),
                ('factura_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion', to='AA.factura')),
                ('subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AA.subasta_evento')),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('metal', models.CharField(max_length=50)),
                ('forma', models.CharField(max_length=50)),
                ('tamano', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('motivo', models.CharField(max_length=50)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('anverso', models.CharField(max_length=50)),
                ('reverso', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('denominacion', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('artistas', models.ManyToManyField(blank=True, default=None, null=True, to='AA.Artista')),
                ('creada_en', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AA.pais')),
                ('divisa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AA.divisa')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=200)),
                ('coleccionista', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='coleccionita_email', to='AA.coleccionista')),
            ],
        ),
        migrations.AddField(
            model_name='divisa',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AA.pais'),
        ),
        migrations.AddField(
            model_name='costo_envio',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AA.pais'),
        ),
        migrations.CreateModel(
            name='Contacto_tienda',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AA.tienda')),
            ],
        ),
        migrations.AddField(
            model_name='coleccionista',
            name='nacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='nacio', to='AA.pais'),
        ),
        migrations.AddField(
            model_name='coleccionista',
            name='vive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vive', to='AA.pais'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('date_client', models.DateField(blank=True, null=True)),
                ('num_coleccionista', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AA.coleccionista')),
                ('num_tienda', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AA.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo_Pintura',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('estilo', models.CharField(max_length=50)),
                ('size', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('coleccionista', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='AA.coleccionista')),
                ('tienda', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='AA.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo_Moneda',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('coleccionista', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='AA.coleccionista')),
                ('moneda', models.ManyToManyField(blank=True, default=None, to='AA.Moneda')),
                ('tienda', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='AA.tienda')),
            ],
        ),
        migrations.AddField(
            model_name='articulo_subasta',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AA.subasta_evento'),
        ),
        migrations.AddField(
            model_name='articulo_subasta',
            name='ganador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AA.participante'),
        ),
        migrations.AddField(
            model_name='articulo_subasta',
            name='moneda',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='AA.Moneda'),
        ),
        migrations.AddField(
            model_name='articulo_subasta',
            name='pintura',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='AA.Catalogo_Pintura'),
        ),
    ]
