# Generated by Django 3.2.4 on 2021-07-14 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subasta_evento',
            name='tiendas',
        ),
        migrations.AddField(
            model_name='subasta_evento',
            name='tiendas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='AA.tienda'),
        ),
    ]
