# Generated by Django 3.2.4 on 2021-07-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AA', '0002_auto_20210714_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subasta_evento',
            old_name='tiendas',
            new_name='tienda',
        ),
    ]
