# Generated by Django 3.2.4 on 2021-07-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AA', '0003_rename_tiendas_subasta_evento_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta_evento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
