# Generated by Django 3.2.4 on 2021-07-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AA', '0004_alter_subasta_evento_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo_pintura',
            name='artistas',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='AA.Artista'),
        ),
        migrations.AlterField(
            model_name='catalogo_pintura',
            name='year',
            field=models.DateField(),
        ),
    ]
