# Generated by Django 3.2.4 on 2021-07-15 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AA', '0005_auto_20210715_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo_pintura',
            name='artistas',
        ),
        migrations.AddField(
            model_name='catalogo_pintura',
            name='artistas',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='AA.artista'),
        ),
    ]
