INSERT INTO public."AA_Moneda"(divisa, creada_en, nombre, tamano, metal, forma, motivo, peso, anverso, reverso, denominacion) VALUES ( 3, 1, 'franco', 2, 'hierro', 'circular','aniversario', 10, 'anverso', 'reverso', '10');
INSERT INTO public."AA_Moneda"(divisa, creada_en, nombre, tamano, metal, forma, motivo, peso, anverso, reverso, denominacion) VALUES ( 4, 2, 'Denario', 2, 'hierro', 'circular','aniversario', 10, 'anverso', 'reverso', '10');
INSERT INTO public."AA_Moneda"(divisa, creada_en, nombre, tamano, metal, forma, motivo, peso, anverso, reverso, denominacion) VALUES ( 5,3, 'Quater', 2, 'hierro', 'circular', 'aniversario',10, 'anverso', 'reverso', '10');
INSERT INTO public."AA_Moneda"(divisa, creada_en, nombre, tamano, metal, forma, motivo, peso, anverso, reverso, denominacion) VALUES ( 2, 4, 'puya', 2, 'hierro', 'circular','aniversario', 9, 'anverso', 'reverso', '10');
INSERT INTO public."AA_Moneda"(divisa, creada_en, nombre, tamano, metal, forma, motivo, peso, anverso, reverso, denominacion) VALUES ( 4, 5, 'reales', 2, 'hierro', 'circular','aniversario', 9, 'anverso', 'reverso', '10');
INSERT INTO public."AA_Moneda"(divisa, creada_en, nombre, tamano, metal, forma, motivo, peso, anverso, reverso, denominacion) VALUES ( 2, 6, 'puya', 2, 'hierro', 'circular','aniversario', 9, 'anverso', 'reverso', '10');
INSERT INTO public."AA_Moneda"(divisa, creada_en, nombre, tamano, metal, forma, motivo, peso, anverso, reverso, denominacion) VALUES ( 7, 7, 'RealesFelipe', 2, 'hierro', 'circular','aniversario', 9, 'anverso', 'reverso', '10');
INSERT INTO public."AA_Moneda"(divisa, creada_en, nombre, tamano, metal, forma, motivo, peso, anverso, reverso, denominacion) VALUES ( 1, 8, 'Dolar', 2, 'hierro', 'circular','aniversario', 9, 'anverso', 'reverso', '10');
INSERT INTO public."AA_Moneda"(divisa, creada_en, nombre, tamano, metal, forma, motivo, peso, anverso, reverso, denominacion) VALUES ( 5, 9, 'Denario', 2, 'hierro', 'circular','aniversario', 9, 'anverso', 'reverso', '10');
